name: "Configure Docker certificates"
description: "Configure Docker certificates to be able to be able to pull/push Docker images
from Kivra's private Docker registry (ie. docker.kivra.net)."
inputs:
  ca:
    required: true
  client_cert:
    required: true
  client_key:
    required: true
  docker_certs_dir:
    default: "/etc/docker/certs.d/docker.kivra.net"
runs:
  using: "composite"
  steps:
    - run: |
        sudo mkdir -p ${{ inputs.docker_certs_dir }}
        sudo chown $(whoami) ${{ inputs.docker_certs_dir }}
        echo "${{ inputs.ca }}" > ${{ inputs.docker_certs_dir }}/ca.crt
        echo "${{ inputs.client_cert }}" > ${{ inputs.docker_certs_dir }}/client.cert
        echo "${{ inputs.client_key }}" > ${{ inputs.docker_certs_dir }}/client.key
        sudo mkdir /etc/systemd/system/docker.service.d
        sudo tee /etc/systemd/system/docker.service.d/schema1.conf > /dev/null <<EOF
        [Service]
        Environment="DOCKER_ALLOW_SCHEMA1_PUSH_DONOTUSE=1"
        EOF
        sudo systemctl daemon-reload
        sudo systemctl restart docker
      shell: bash